version: '3.8'

services:
  db:
    image: postgres:14.7-alpine
    restart: always
    env_file: ".env"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alias-arena
    env_file: ".env"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: alias-arena-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db