version: '3.8'

services:
  postgres:
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    networks:
      - postgres

  nestjs-api:
    image: nestjs-api
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge